name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '1 0/4 * * *'
permissions:
  contents: write
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Update and Build
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        ./run.sh
